### ISSUE TITLE
as convert ByteBuffer to Ogg Vorbis?

### ISSUE THREAD

**Issue by fums** [Gagravarr/VorbisJava#18]
I receive audio data (RAW audio) by websocket and I need to encode to Ogg Vorbis, how could it?

```Java
...
public void onMessage(WebSocket ws, ByteBuffer buffer) {
        //System.out.println(buffer);
        //HERE encoder buffer to ogg
}
...
```

help :(
Regards

**Comment by Gagravarr** [comment]
There is no Encoding support in the library at the moment, sorry, and given the complexity involved I'm not sure it ever will be

Likely your best bet is to fire up a worker thread, have that spawn a copy of the command line VorbisEnc tool (with appropriate options for quality, input from stdin etc), have that feed the raw audio to the stdin of the process, and grab the resulting ogg file from stdout for sending on / storing / etc
