### ISSUE TITLE
JavaDoc Information Missing from Tika 1.17?

### ISSUE THREAD

**Issue by SarahSzabo** [Gagravarr/VorbisJava#25]
I've set my project to use the JavaDoc from (https://tika.apache.org/1.17/api/), but the JavaDoc information is still missing from. I'm using a Tika 1.17 Jar on the classpath in Netbeans. Where can I find the Gagravarr Javadoc to attach it to my Tika 1.17 library to restore the JavaDoc of classes such as OPUSFile?

**Comment by Gagravarr** [comment]
You can get the javadoc jar from your favourite Maven mirror, eg http://central.maven.org/maven2/org/gagravarr/vorbis-java-core/0.8/ -> http://central.maven.org/maven2/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8-javadoc.jar and http://central.maven.org/maven2/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8-javadoc.jar

I've no idea about any Netbeans stuff though, you'll need to ask on the netbeans users list or support forum for help there.
